FROM mongo

COPY lorem.json /lorem.json
COPY flag.json /flag.json

CMD mongoimport --drop --host mongodb --db reach-humanity --collection messages --type json --file /lorem.json --jsonArray && mongoimport --drop --host mongodb --db reach-humanity --collection flag --type json --file /flag.json --jsonArray
